### PR TITLE
Add pre-commit containing ruff linter

### PR DESCRIPTION
**Pull request by rht**
I don't exactly remember how to enable pre-commit in a GH repo (https://pre-commit.com/#plugins) but it should look like this: https://results.pre-commit.ci/run/github/42205414/1705017304.m3mnZTHiQ3eC9mW3YS30Iw.

### CODE REVIEW

**Comment by rht** [comment]
Whoops, I meant the linter. The whole codebase had only been linted, not formatted.

**Comment by rtvuser1** [comment]
What is the impact of this on developers?
When I go to do a commit on code I just edited, does it simply give me warnings about lint issues?
Or does it prevent me from committing my files?

**Comment by rht** [comment]
> When I go to do a commit on code I just edited, does it simply give me warnings about lint issues?

Yes, it won't block PR's. It simply gives warnings. But you have to manually enable it in https://pre-commit.com/#plugins.

**Comment by rtvuser1** [comment]
If I don't have it enabled via the plugin, will there be errors?

**Comment by rtvuser1** [comment]
Merging to develop. Will test for side effects before before merging to master

**Pull request merged**
