### PR TITLE
Cleaned up notebook templates

### PR DESCRIPTION
**Pull request by japanavi**
- Added markdown headings above each benchmark cell for easier navigation.
- Deleted run magic commands because they were redundant and didn't allow user to specify any new arguments.

### CODE REVIEW

**Review by rtvuser1 — CHANGES_REQUESTED** [review]
It looks like in the cirq notebook, you added a method parameter and cell for monte carlo method 1.
I believe that in Qiskit and Braket we assume method 2 by default and do not expose it as an option in the notebook.  (there was some reason that I do not remember now). 
We should make these consistent and modify the cirq notebook to NOT have method 1

Also, I thought the projectq notebook had been removed, but it seems to be there. 
I think we should remove that notebook entirely as we no longer support projectq at all

**Comment by japanavi** [comment]
Thanks! 

Re Cirq Notebook: Do you want me to remove the method parameter in this PR? Or should I just do all of the formatting changes and submit a new PR for the removal of the method parameter?

Re projectq Notebook: It was (and still is) present in the master branch of the repository when I was doing these edits, so I figured I would add the changes to it as well. Would you like me to delete it in this PR?

**Comment by rtvuser1** [comment]
Yes, remove method parameters, so it looks like the others.And yes, just delete the projectq notebookBoth of above can be part of the current PRSent via the Samsung Galaxy S8 Active, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Joshua Apanavicius ***@***.***> Date: 5/18/22  12:41 PM  (GMT-08:00) To: SRI-International/QC-App-Oriented-Benchmarks ***@***.***> Cc: Tom Lubinski ***@***.***>, Comment ***@***.***> Subject: Re: [SRI-International/QC-App-Oriented-Benchmarks] Cleaned up
  notebook templates (PR #70) 
Thanks!
Re Cirq Notebook: Do you want me to remove the method parameter in this PR? Or should I just do all of the formatting changes and submit a new PR for the removal of the method parameter?
Re projectq Notebook: It was (and still is) present in the master branch of the repository when I was doing these edits, so I figured I would add the changes to it as well. Would you like me to delete it in this PR?

**Review by rtvuser1 — APPROVED** [review]
Merging Now

**Pull request merged**
