### PR TITLE
Cirq: Added functions to get transpiled metrics which helps to generate the Volumetric Positioning Plot

### PR DESCRIPTION
**Pull request by GIRISHBELANI**
1. In execute.py, added functions to get transpiled metrics which helps to generate the Volumetric Positioning Plot
2. changes done in some benchmarks for proper calculation of counts and correct_dist in analyze_and_print_result()

***Screenshots from the benchmarks are attached for reference.

Amplitude-Estimation-metrics
Amplitude-Estimation-vplot
Bernstein-Vazirani-metrics
Bernstein-Vazirani-vplot
Deutsch-Jozsa-metrics
Deutsch-Jozsa-vplot
Grover's-Search-metrics
Grover's-Search-vplot
Hamiltonian-Simulation-metrics
Hamiltonian-Simulation-vplot
Hidden-Shift-metrics
Hidden-Shift-vplot
Monte-Carlo-Sampling-(2)-metrics
Monte-Carlo-Sampling-(2)-vplot
Phase-Estimation-metrics
Phase-Estimation-vplot
Quantum-Fourier-Transform-metrics
Quantum-Fourier-Transform-vplot

### CODE REVIEW

**Review by rtvuser1 — CHANGES_REQUESTED** [review]
Thanks for splitting this PR out separately and for all the images of the results. This is an improvement over what we have.  However, before merging, I want to point to the difference in some of the depth metrics computed, as compared to the Qiskit version. 
For example, the Algorithmic depth of the Amplitude Estimation circuits is very different in Qiskit than in the plot you created in Cirq. There may be an explanation for it.  Can you investigate the reason.  In AE, the Normalized depth is very similar (I'd expect minor differences due to the compiler). But the Algortihmic depth should be the same or similar.
There are other examples too.  The Quantum Fourier Transform's Algorithmic depth is constant, which really should not be the case.  As the circuit width grows, the number of gates should be increasing.
Here is the Qiskit version of AE for comparison.
Amplitude-Estimation-metrics

**Comment by GIRISHBELANI** [comment]
> Thanks for splitting this PR out separately and for all the images of the results. This is an improvement over what we have. However, before merging, I want to point to the difference in some of the depth metrics computed, as compared to the Qiskit version. For example, the Algorithmic depth of the Amplitude Estimation circuits is very different in Qiskit than in the plot you created in Cirq. There may be an explanation for it. Can you investigate the reason. In AE, the Normalized depth is very similar (I'd expect minor differences due to the compiler). But the Algortihmic depth should be the same or similar. There are other examples too. The Quantum Fourier Transform's Algorithmic depth is constant, which really should not be the case. As the circuit width grows, the number of gates should be increasing. Here is the Qiskit version of AE for comparison. Amplitude-Estimation-metrics

The lack of decomposition in Cirq means that complex, higher-level gates aren't broken down into their constituent operations, leading to underreported Algorithmic depth. In Qiskit, circuits are decomposed into a standard gate set, providing a more detailed depth calculation. This explains why the Algorithmic depth in QFT remains constant in Cirq, as the growing complexity of controlled rotations isn't fully captured without decomposition.

**Comment by rtvuser1** [comment]
Yes, the fact that the top-level circuit includes one instance of the QFT gate and the IQFT gate results in there being an algorithmic  gate depth of 5.  In Qiskit, we construct the circuit the same way, but we use the decompose() function on the circuit afterwards to expand it to a larger number of gates, but with out transpilation. Isn't there a way to do something similar for Cirq?  Or perhaps the algorithm you use in execute.py could traverse the hierarchy to count the gates?  
It is good that we can transpile and get a Normalized Depth, but sometimes we use the Algorithmic Depth ... it would be useful if that aligned across APIs.
Before closing or merging this PR, can you look to see if there is some way to address this?

**Comment by GIRISHBELANI** [comment]
"For Cirq, we can use qc = cirq.Circuit(cirq.decompose(op) for op in qc.all_operations()) for circuit decomposition. If this approach works for you, we can apply it across all algorithms."

***Screenshots from the AE and QFT benchmarks are attached for reference.
Quantum-Fourier-Transform-metrics
Quantum-Fourier-Transform-vplot

Amplitude-Estimation-metrics
Amplitude-Estimation-vplot

**Comment by rtvuser1** [comment]
Well, that looks better in terms of the Algorithmic depth for QFT.  At 8 qubits it looks like A.D. is about 48.  In Qiskit, howeer, the A.D. is more like 75.  So there is some discrepancy that should be looked at. At the topmost level, it seems like the gate dpth should be very similar. It may be something about how the gates are parallelized that leads to the difference.
However, the Normalized depth for both QFT and AE is lower than the A.D. ... this seems incorrect, although I suppose the transpiler could be collapsing gates more in Cirq than in Qiskit.
Note: I am prepared to merge this PR if you think this is good enough... it is better than having not depth info.  But, the depths for Cirq will not align.
It would be helpful if you can determine whether the Normalized Depth truly is lower than Algorithmic Depth, by printing the circuit before and after transpilation.
Let me know here whether you'd like to go ahead and merge it with this anomaly or not.

**Comment by GIRISHBELANI** [comment]
Circuit decomposition has been added for all benchmarks, which generally leads to an increase in Algorithmic depth. However, the Normalized depth is lower due to the specific transpilation strategy used. By utilizing the CZTargetGateset() along with 
 optimize_for_target_gateset(), the circuit is compiled to leverage the efficiency of CZ gates and other  compatible gates, which are naturally suited for the target architecture. This optimization reduces the circuit's overall depth when mapped to this specific gate set, resulting in a lower Normalized depth compared to the Algorithmic depth.
Additionally, since Cirq does not have explicit barriers like other frameworks, optimization and reordering of operations can further impact depth.

**Comment by rtvuser1** [comment]
Since the PR has been active for a while and you have made good progress, I will merge in what you have.

However, I think there may still be some refinements that could be made to the circuit depth calculations. In the Qiskit version we transpile to the gate set denoted by [‘rx’, ‘ry’, ‘rz’, ‘cx’] in Qiskit. This is a widely used universal basis [34] that is hardware-agnostic.
This approach is described in detail on page 9 of https://arxiv.org/abs/2110.03137
Ideally in Cirq we would transpile to this same gate for displaying the depth plots, including the volumetric plots, so that the circuit depths align.
If you do not see an easy way to accomplish this, then we should create an Issue for this to be addressed later.

**Pull request merged**
