### PR TITLE
Adding Qatalyst support

### PR DESCRIPTION
**Pull request by thisisaus**
This PR contains support for the QCi Qatalyst API and the hardware devices it supports (issue #426). The maxcut benchmark is implemented as well. Some graphics are disabled, but most metrics are printed, even if they aren't relevant due to Qatalyst not supporting gate model circuits. There is also a code change to the `metrics.py` to address issue #425.

Reference documentation on Qatalyst: https://qatalyst.quantumcomputinginc.com

### CODE REVIEW

**Review by rtvuser1 — COMMENTED** [review]
This looks very interesting.
a few questions and comments:

1) The change to metrics does not seem necessary. Why would the group argument ever be "subtitle".  When the store_metric method is called, it should always be called with the circuit width, or in the case of maxcut, the problem size.  The subtitle is normally set in another method called during execution, but not with circuit metrics.

2) In the ocean/maxcut folder there is a notebook file, benchmarks-ocean-add-maxcut.ipynb where the user can configure the benchmark arguments and execute the run() method. You would need to add a notebook like this to make this benchmark like others.

The ocean version of the maxcut benchmark is a little behind the qiskit version in some aspects.  We can address this later. For now, you can make the qatalyst version similar to the ocean version.

Does the qatalyst version work the same as the ocean version?  Do you execute multiple times at different annealing settings in order to mimic the behavior of the gate model system execution time?

It might be useful to arrange a demo of what you are doing to be sure it is executing the benchmarks properly.

**Comment by thisisaus** [comment]
1. I agree it does not seem like it should be necessary. The comment on issue #425 at https://github.com/SRI-International/QC-App-Oriented-Benchmarks/issues/425#issuecomment-1791859474 describes the core issue. Rather than refactor the way subtitle gets passed to the plots myself, I added these checks to allow the metrics code to run.
2. I will add a notebook to run the benchmarks like the others, rather than as a command line script.

Right now, the device that this benchmark has been run with does not support user-specified settings like the quantum annealer in ocean. The next major update to qatalyst does have settings for some hardware control. This can be added to the benchmark code when the API supports it. 

I'd be happy to schedule a demo of this when I add the notebook.

**Comment by thisisaus** [comment]
In both the qiskit and ocean `maxcut_benchmark.py` files, the "subtitle" key is added directly to the dictionary in the `save_runtime_data` method. I left it when I copied from the ocean benchmarks. I think that it was added at a time when it seemed like a convenient way to pass the configured plot subtitle without changing method signatures.

**Comment by qci-github** [comment]
I've added a notebook and cleaned up a number of pieces of code. 

Let me know if I should go in a different direction with the update to `metrics.py`. It will be a larger change, but I see the benefit of passing subtitle in a different place.

**Comment by thisisaus** [comment]
> I've added a notebook and cleaned up a number of pieces of code.
> 
> Let me know if I should go in a different direction with the update to `metrics.py`. It will be a larger change, but I see the benefit of passing subtitle in a different place.

I was logged in as the wrong user when making this comment.

**Comment by rtvuser1** [comment]
We will take another look at what you have proposed.  Work is picking up again on the maxcut benchmark and we will be able to review this and make a suggestion.
It would be best if you could close this PR and then regenerate it after pulling code from the "develop" branch.  Make the new PR back to the develop branch, rather than master.

**Comment by thisisaus** [comment]
Closing this to code against the latest.

**Pull request closed without merging**
